# Generated by Django 5.0.1 on 2024-02-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low_priority', 'Low_priority'), ('Medium_priority', 'Medium_priority'), ('High_priority', 'High_priority')], default='High_priority', max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
