# Generated by Django 5.0.1 on 2024-01-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerid', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Salary', models.IntegerField()),
                ('City', models.CharField(max_length=200)),
            ],
        ),
    ]
